SET FOREIGN_KEY_CHECKS = 0;
TRUNCATE `user`;
TRUNCATE `user_order`;
TRUNCATE `ingredient`;
TRUNCATE `recipe_ingredient`;
TRUNCATE `recipe`;
TRUNCATE `category`;
TRUNCATE `menu`;
TRUNCATE `order`;
TRUNCATE `order_menu`;
SET FOREIGN_KEY_CHECKS = 1;